// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD_3ASpfTlDwo-Eg0NoXcPKVpjBt75Pg8',
    appId: '1:468430333427:web:6651725ae816de708f5e86',
    messagingSenderId: '468430333427',
    projectId: 'registration-app-cc6e2',
    authDomain: 'registration-app-cc6e2.firebaseapp.com',
    storageBucket: 'registration-app-cc6e2.appspot.com',
    measurementId: 'G-RS374JRNYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSOvvHh-ELWA_Ow3wFMO850n8LTYqbgI',
    appId: '1:468430333427:android:14f79f8b049a6d598f5e86',
    messagingSenderId: '468430333427',
    projectId: 'registration-app-cc6e2',
    storageBucket: 'registration-app-cc6e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxKKd1snUsTzYv8FArTu9BIsL1eahrXNw',
    appId: '1:468430333427:ios:e31d86a3642a9bfe8f5e86',
    messagingSenderId: '468430333427',
    projectId: 'registration-app-cc6e2',
    storageBucket: 'registration-app-cc6e2.appspot.com',
    iosBundleId: 'com.example.registrationApp',
  );
}
